### ISSUE TITLE
Extension produces "tsserver was deleted"

### ISSUE THREAD

**Issue by Sinmson** [VitalyKondratiev/vscode-sshextension#9]
When I load typescript apps in vscode I get this error message and the intellisense is deactivated. 

![2018-08-14 09_43_08-](https://user-images.githubusercontent.com/9356355/44078456-cd31716e-9fa6-11e8-950b-06f01f3101c2.png)

At first I thought it is a VS Code bug as written in the error message. So I reinstalled it and made it portable to have a clean version. I started to install my extensions and opened my typescript project and the message appeared again. I started deinstalling all extension and testing each one. And this extension causes this error.

That deactivates the intellisense. So I can press cntrl + space and only get a random list of words because vs code tsserver does not work.

Errors in developer console:
![2018-08-14 10_05_13-extension_ sshextension - lightbsm - visual studio code](https://user-images.githubusercontent.com/9356355/44079524-98466c86-9fa9-11e8-924b-61c06cb90a6d.png)
![2018-08-14 10_05_48-extension_ sshextension - lightbsm - visual studio code](https://user-images.githubusercontent.com/9356355/44079548-a92bf94e-9fa9-11e8-97f5-ba0a3dc7e023.png)

Printed:

```
INFO no standard startup: not a new window

[Extension Host] Activating extension 'vscode.typescript-language-features' failed: Could not find bundled tsserver.js.

[Extension Host] Activating extension `vscode.typescript-language-features` failed:  Could not find bundled tsserver.js

[Extension Host] Here is the error stack:  Error: Could not find bundled tsserver.js
	at TypeScriptVersionProvider.get bundledVersion [as bundledVersion] (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\extensions\typescript-language-features\out\utils\versionProvider.js:132:15)
	at TypeScriptVersionProvider.get defaultVersion [as defaultVersion] (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\extensions\typescript-language-features\out\utils\versionProvider.js:88:42)
	at new TypeScriptVersionPicker (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\extensions\typescript-language-features\out\utils\versionPicker.js:21:52)
	at new TypeScriptServiceClient (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\extensions\typescript-language-features\out\typescriptServiceClient.js:161:30)
	at new TypeScriptServiceClientHost (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\extensions\typescript-language-features\out\typeScriptServiceClientHost.js:53:23)
	at LazyValue.lazy_1.lazy [as _getValue] (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\extensions\typescript-language-features\out\extension.js:53:28)
	at LazyValue.get value [as value] (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\extensions\typescript-language-features\out\utils\lazy.js:15:32)
	at didOpenTextDocument (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\extensions\typescript-language-features\out\extension.js:34:32)
	at activate (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\extensions\typescript-language-features\out\extension.js:44:13)
	at Function.t._callActivateOptional (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:791:650)
	at Function.t._callActivate (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:791:329)
	at c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:790:391
	at Object.g [as _notify] (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:729)
	at Object.enter (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:61)
	at n.Class.derive._oncancel._run (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:866)
	at n.Class.derive._oncancel._completed (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:307)
	at c (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:785)
	at $.then.o.(anonymous function) (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:999)
	at Object.g [as _notify] (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:729)
	at Object.enter (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:61)
	at n.Class.derive._oncancel._run (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:866)
	at n.Class.derive._oncancel._completed (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:307)
	at c (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:785)
	at $.then.o.(anonymous function) (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:999)
	at Object.g [as _notify] (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:729)
	at Object.enter (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:61)
	at n.Class.derive._oncancel._run (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:866)
	at n.Class.derive._oncancel._completed (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:307)
	at e.resolveOk (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:554:1000)
	at e._receiveReply (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:394)
	at e._receiveOneMessage (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:693)
	at c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:655:544
	at c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:673
	at c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:599
	at e.fire (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:97:917)
	at u (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:721)
	at Socket.<anonymous> (c:\Users\A76286665\Downloads\VSCode-win32-x64-1.25.1\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:898)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)

VS Code's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VS Code.
   e.onDidNotificationChange @ notificationsAlerts.ts:42

Activating extension 'vscode.typescript-language-features' failed: Could not find bundled tsserver.js.
  w._logMessageInConsole @ extensionService.ts:892
```

**Comment by VitalyKondratiev** [comment]
Thank you for created issue. I fixed this today. Please update the extension on your machine.

**Comment by tokenflow** [comment]
I have the same error, enabling the "TypeScript and JavaScript Language Features" extension solved my issue
<img width="1052" alt="Screen Shot 2019-04-12 at 6 41 22 PM" src="https://user-images.githubusercontent.com/8538953/56045855-12c3c780-5d53-11e9-89d1-5a51209385b4.png">
